apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ecr-update-token
spec:
  schedule: "0 */10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ecr-update-token
              image: viniciuslsdias/kubectl-aws
              command: 
              - /bin/sh
              - -c
              - |-
                kubectl delete secret --ignore-not-found aws-registry
                TOKEN=`aws ecr get-login --no-include-email --region $REGION | awk '{ print $6 }'`
                kubectl create secret docker-registry aws-registry --docker-server=https://${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com --docker-username=AWS --docker-password=$TOKEN
                kubectl patch serviceaccount default -p '{"imagePullSecrets":[{"name":"aws-registry"}]}'
              env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_ACCESS_KEY_ID
      
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_SECRET_ACCESS_KEY
            
              - name: REGION
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: REGION
            
              - name: ACCOUNT_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: ACCOUNT_ID
      
          restartPolicy: OnFailure
